### ISSUE TITLE
No Acces to foutons of remote CouchDB

### ISSUE THREAD

**Issue by codingfabi** [NGO-DB/ndb-core#185]
We would like to add some dummydata to the test database so we could test the ChildSchoolRelation that @TheSlimvReal implemented. 
Currently we have no access to the couchdb.aam-digital.com/_utils due to authentication errors. 
Can we have a user with wich wie have acces rights?

**Comment by sleidig** [comment]
For testing the best way is to add dummy data to the `MockDatabase` (which simulates only a temporary database in memory) through code in the `DemoData` class (database module). That way you can also do unit tests and you can tinker with an automatically reset data.

Futon access is a little messed up. You need to log in through our app for authentication and then open the futon page because the popup login window of CouchDB is disabled. I'll create a dev admin user and share it in Slack.

**Comment by Lorsbyjm** [comment]
@codingfabi can we close this?

**Comment by codingfabi** [comment]
Yes, can be closed
