### ISSUE TITLE
CORS policy on dev-db

### ISSUE THREAD

**Issue by liwde** [NGO-DB/ndb-core#243]
Currently, when the temporaryDatabase is disabled, the remote database can not be connected. This affects the master and both Firefox and Chrome.

@sleidig, did you make any changes to the setup of the dev-database?

`Access to XMLHttpRequest at 'https://demo.aam-digital.com/db/_session' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by sleidig** [comment]
The live systems use our docker-compose setup (https://github.com/NGO-DB/docker), so this can be locally replicated and worked on if you install docker.

Indeed, when we switched to docker, we got a new server configuration that is probably missing somethings for these cases. 

We are generally working with a reverse proxy, making CouchDB accessible at the same URL as the hosted app (https://server-url.com/db), which avoids any CORS issues for the live system.

I couldn't figure out a solution yet how to allow the dev systems running on localhost:4200 to access the demo CouchDB anyways. Not sure whether CouchDB or the nginx server doing the reverse proxy are blocking it due to CORS ...

**Comment by TheSlimvReal** [comment]
As a workaround, you can start Chrome with disableded web security, which allows CORS. You just need to enter the command:

> Chrome --disable-web-security --disable-gpu --user-data-dir=~/chromeTemp

If the command chrome is not found, run the command from the folder where the chrome executable is stored.

**Comment by sleidig** [comment]
I managed to activate CORS (`Access-Control-Allow-Origin: *`) at the demo db now so we can use it for development without hassle.
(Turns out Fauxton, the CouchDB GUI, has a button for that)
