### ISSUE TITLE
new install won't use local database after logging in with demo

### ISSUE THREAD

**Issue by bkolaci** [NGO-DB/ndb-core#47]
I did a local install, and have a local couchdb running.
After a build, ran the program and was able to login with demo/pass.
Apparently it logged into the default: http://demo-db.sinnfragen.org/db/ as set in the config.service.
I changed that to http://localhost:5984/db/ which still accepts the demo/pass login, but doesn't show anything on the screen.  There's nothing in the local couchdb either.

Not sure how to recover this, and how to build a fresh database to make the app work.

Is there a pre-populated database required with credentials added?
Can you provide what information is required in the db to start a new instance?

**Comment by fschoell** [comment]
Yes you need at least one user in your database, you can't use an empty database. This is due to the requirement of the offline functionality, the credentials are actually used twice. First to authenticate at the CouchDB server to enable the synchronization and then to authenticate using the local database (otherwise we can't log a user in if he is offline).

Adding users is currently not supported (but on the todo list) and has to be done manually. For the password we use PBKDF2 with the options and salt stored in the database. The hashing can be found in the `user.ts` file. 

Here is our demo user, just add the json to your local database (if you use chrome there's the PouchDB Inspector extension which can do that): 
```
{
  "_id": "user:demo",
  "name": "demo",
  "password": {
    "hash": "220dbb88804bd863739611322ad23b026626d7c457a2dd004cbadec9ba83ee2b",
    "salt": "4754c4bba257a8af92e11cfe6c176640",
    "iterations": 128,
    "keysize": 8
  }
}
```

If you want multiple user, just add the demo user with a different id and name. Changing the password is supported in our application, you don't need to manually create the hashes.

**Comment by sleidig** [comment]
yes, initial setup is not really supported at the moment. However, there is a script (js) that can be run on a server to add a user or change its password, that has not been moved to this new repository: https://github.com/NGO-DB/helgo_db/blob/master/add-user.js
