### ISSUE TITLE
Add functionality to the EntityMapperService and rewrite the entity class

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/ndb-core#54]
EntityMapperService:

 - [x] We need the functionality to load lists of entities (like all children). The EntityMapperService should be extended to load those lists by prefix. 
 - [x] Maybe to save lists of entities, too? 
 - [x] We should find a solution to handle references.

Entity Class: 

 - [x] The entity id should be final as it's not allowed to change it later.
 - [x] We might need to rethink the getPrefix() method. Not sure if we should allow empty prefixes. In my opinion we should make this method either abstract so it has to be implemented by any child class or we use the class name as prefix instead (this way we could detatch the id handling completely from the actual entity classes, it only knows the actual id without any prefixes).
- [x] Write documentation how new sub Entity classes should be created: [Wiki - Creating new Entity types](https://github.com/NGO-DB/ndb-core/wiki/Creating-new-Entity-types)

also see PR #68, #84

**Comment by fschoell** [comment]
@sleidig Your opinion on this?

**Comment by sleidig** [comment]
#### Save lists of entities
I think this probably won't be needed. Stuff should be created/updated one by one anyway?

#### Handle References
Yes, a good solution for this is definitely needed. In fact the idea was that EntityMapperService should later be extended as to resolve any references of a loaded entity before returning it, so that it contains references to instances of any linked entities.
Although loading all links at once is probably slowing down things and there should be some "lazy loading" mechanism.

For the time being, maybe create a "referenced entity" class that contains the id and a function to resolve (i.e. load) the reference?

#### Entity.getPrefix()
Yes, this is actually quite ugly. I would prefer to make the prefix completely transparent - doing something based on class names might be a good solution but seemed a little to complicated and hacky when I created the first entity stubs

**Comment by sleidig** [comment]
Long, but rather insightful article about document databases vs. relational databases. I'm starting to more and more think we'd be better off with SQL.
http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/

We chose CouchDB only for the out of the box, full sync with the local JavaScript implementation PouchDB. Despite some doubts of not using a relational db.

Maybe there is some relational DB with 2-way sync available nowadays?

**Comment by Lorsbyjm** [comment]
Hi,
ich hab einfach mal gegoogelt und das gefunden, vllt hilft es:
https://xamarinhelp.com/mobile-database-bi-directional-synchronization-rest-api/

**Comment by sleidig** [comment]
After looking into this further I would recommend we stick to PouchDB. The library is well maintained and the sync seems better than other's. However, we should carefully abstract that choice beneath the `Database` class and the relationship/reference handling beneath `EntityMapperService` so we can possibly change later on. Also, with our `MockDatabase` for testing and dev we already have a non-PouchDB implementation.

The reference handling will need to be implemented by us in `EntityMapper` (and possibly in special sub-classes for specific entity types), even _relational-pouch_ doesn't create nested json objects.

**Comment by sleidig** [comment]
_relational-pouch_ may still be interesting. Maybe their implementation is easier to understand and more optimized than our own using prefixes. But this would only affect the implementation of `PouchDatabase` class because the `Database` layer is abstracted (and `MockDatabase` is completely our own implementation anyway).

**Comment by sleidig** [comment]
Recently I produced another layer, `ChildrenService`, on top of `EntityMapperService`. I think this is getting confusing now. Anyway, `ChildrenService.getChildren()` and the like are only passing the things through to the EntityMapper. Probably instead of using `ChildrenService` we should use `EntityMapperService` directly.

**Comment by sleidig** [comment]
**Handling References:**
It's not only difficult but also bad for performance if we would automatically load all references of an entity automatically. For now, every component or service that needs that referenced object has to load that referenced entity explicitly using the EntityMapper.

While advance, elegant generalizations of this are imaginable, let's keep it at that for the time being. I think the key points of this issue are therefore resolved.
